# Generated by Django 6.0.7 on 2026-07-27 10:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('jobs', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BoostOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('boost_type', models.CharField(choices=[('worker_profile', 'Tezkor ish topish (usta profili)'), ('job_post', "Tezkor buyurtma (ish e'loni)")], max_length=20, verbose_name='Turi')),
                ('amount', models.PositiveIntegerField(verbose_name="Summasi (tiyin, ya'ni so'm x 100)")),
                ('status', models.CharField(choices=[('kutilmoqda', "To'lov kutilmoqda"), ('tolangan', "To'langan"), ('bekor_qilingan', 'Bekor qilingan')], default='kutilmoqda', max_length=20, verbose_name='Holati')),
                ('payme_transaction_id', models.CharField(blank=True, db_index=True, max_length=64, verbose_name='Payme tranzaksiya ID')),
                ('payme_state', models.IntegerField(blank=True, null=True, verbose_name='Payme holati (1=yaratildi,2=amalga oshdi,-1/-2=bekor)')),
                ('payme_create_time', models.BigIntegerField(blank=True, null=True, verbose_name='Payme create_time (ms)')),
                ('payme_perform_time', models.BigIntegerField(blank=True, null=True, verbose_name='Payme perform_time (ms)')),
                ('payme_cancel_time', models.BigIntegerField(blank=True, null=True, verbose_name='Payme cancel_time (ms)')),
                ('payme_reason', models.IntegerField(blank=True, null=True, verbose_name='Bekor qilish sababi (Payme kodi)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan sana')),
                ('expires_at', models.DateTimeField(blank=True, null=True, verbose_name='Boost tugash vaqti')),
                ('job', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='boost_orders', to='jobs.jobpost', verbose_name="Ish e'loni (agar job_post bo'lsa)")),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='boost_orders', to=settings.AUTH_USER_MODEL, verbose_name='Foydalanuvchi')),
            ],
            options={
                'verbose_name': 'Tezkor xizmat buyurtmasi',
                'verbose_name_plural': 'Tezkor xizmat buyurtmalari',
                'ordering': ['-created_at'],
            },
        ),
    ]
