# Generated by Django 6.0.7 on 2026-07-17 10:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('workers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='JobPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Sarlavha')),
                ('description', models.TextField(verbose_name='Tavsif')),
                ('budget', models.DecimalField(blank=True, decimal_places=0, max_digits=12, null=True, verbose_name="Byudjet (so'm)")),
                ('address', models.CharField(blank=True, max_length=255, verbose_name='Manzil')),
                ('status', models.CharField(choices=[('ochiq', 'Ochiq'), ('yopiq', 'Yopiq')], default='ochiq', max_length=10, verbose_name='Holati')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name="E'lon qilingan sana")),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='job_posts', to='workers.workercategory', verbose_name='Kategoriya')),
                ('employer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_posts', to=settings.AUTH_USER_MODEL, verbose_name='Ish beruvchi')),
            ],
            options={
                'verbose_name': "Ish e'loni",
                'verbose_name_plural': "Ish e'lonlari",
                'ordering': ['-created_at'],
            },
        ),
    ]
